// <auto-generated />
namespace AnkhMorporkCourseExercise.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedPub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPub));
        
        string IMigrationMetadata.Id
        {
            get { return "202112141633165_addedPub"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
